import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import ToastProvider from "@/providers/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        http-equiv="Content-Security-Policy"
        content="upgrade-insecure-requests"
      />
      <meta property="twitter:image" content="Twitter link preview image URL"/>
      <meta property="twitter:card" content="summary_large_image"/>
      <meta property="twitter:title" content="Twitter link preview title"/>
      <meta property="twitter:description" content="Twitter link preview description"/>
      <meta property="og:image" content="Link preview image URL"/>
      <meta property="og:site_name" content="Link preview site name"/>
      <meta property="og:title" content="Link preview title"/>
      <meta property="og:description" content="Link preview description" />
      <meta property="og:url" content="Canonical link preview URL"/>
      <body className={inter.className}>
        <ToastProvider />
        <NextAuthSessionProvider>
          <Providers>{children}</Providers>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
